name: CI Tests

on:
  push:
    branches:
      - develop
      - release
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . pytest pytest-cov

      - name: Run tests with coverage
        run: |
          set -o pipefail
          pytest --cov=orion --cov-report=term-missing --cov-report=xml | tee pytest-coverage.txt

      - name: Publish test summary
        if: success()
        run: |
          COVERAGE_PERCENT=$(python - <<'PY'
import xml.etree.ElementTree as ET

tree = ET.parse('coverage.xml')
line_rate = float(tree.getroot().attrib.get('line-rate', 0))
print(f"{line_rate * 100:.2f}")
PY
          )
          {
            echo "### ✅ Pytest suite completed successfully";
            echo "";
            echo "- **Coverage:** ${COVERAGE_PERCENT}%";
            echo "";
            echo '```';
            cat pytest-coverage.txt;
            echo '```';
          } >> "$GITHUB_STEP_SUMMARY"
